BBBB BBBB

XXXX XXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Card Name') XXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXX X
                  XXXXXXXXXXXXXX X
                      XXXXXXXXXXXX XXXXXX
                      XXXXXXXXX XXXXXX
                      XXXXX XXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX XXXXXX
                      XXXXXXXXX XXXXXX
                      XXXXXXXXXXXX XXXXXXX XXXXXXXXX
              XXXXXX
          XXXXXX
          XXXXXX XXX XXXXXXXXXX XXX XXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Node to update') XXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXX X
                  XXXXXXXXXXXXXX X
                      XXXXXXXXXXXX XXXXXX
                      XXXXXXXXX XXXXXX
                      XXXXX XXXXXXXX
                      XXXXXX XXXXXXXXXXXX
                      XXXXXXXXXXX XXXXXX
                      XXXXXXXXX XXXXXX
                      XXXXXXXXXXXX XXXXXXX XXXXXXXXX
              XXXXXX
          XXXXXX
          XXXXXXXXXX
          
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XX

          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XX

          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX

          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX

      XXXXXX
    XXXXXX

  XXXXXX
XXXXXX
