XXXX
XXXXXX X X XXXXXXX XXXXXXXXX XX XXXXXXXXX XXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXX
XXXXXXXXX XXX XXXX XX XXXX XXXXX XXXXX XXX XXXXX XXXXXXXXX XXXX

XXXX XXXXXXX XX XXXX XXXXXXXXX XXX XXX XXXXXXXXXXXX XX XXXXXX XXXXXX
XX XXXXX XXX XXXXX XX XXX XXX XXXXXX XXXXXXX XXXXXX XXXXXXX XX
XXXXXXXXX XX XXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX X XX XXX
XXXXXXXX XX XXX XXXX XXXXXXX XXX XXXXX XXXXXXXX

XXXX XXXXXXX XX XXXXXXXXXXX XX XXX XXXX XXXX XX XXXX XX XXXXXXX
XXX XXXXXXX XXX XXXXXXXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXX XX
XXXXXXXXXXXXXXX XX XXXXXXX XXX X XXXXXXXXXX XXXXXXXX XXX XXX
XXX XXXXXX XXXXXXX XXXXXX XXXXXXX XXX XXXX XXXXXXXX

XXX XXXXXX XXXX XXXXXXXX X XXXX XX XXX XXX XXXXXX XXXXXXX XXXXXX XXXXXXX
XXXXX XXXX XXXX XXXXXXXX XX XXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
BBBB BBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB

XXXXXXXXX XXXXX
XXXXXXX XX XXX XXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
XXXXXXX XX XXX XXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
XXXXXXX XXXXXXXXXX
XXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXX

XXXXXX
    XXXXXXXXXXXXXXX

    XXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXX X XXX X
            XXXXXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXX
        X

        XXXXXX X
            XXXXXX XXXXXX
        X

    XXXXXXXX

XXXXXXX

XXXX
XXX XXXXXXXXX XX XX XXXX XX XXX XXXXXXXXX XXXXXXXX
XXX XXXXXXXX XXX XXXXXXXXXXX XXX XXXX XX XXX XXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
XXX

XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXX X
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXX XXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX  XXX
                        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                             XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
                        XXXX
                    XXXX XXXXXX XXX
                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXX XXX XXX XXXXXXXXXXX
                        XXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX XXXX XXXXXXXXXXXXXXX XXX XXX XXXX XXXXXXXXXXX
                        XXXX
                XXXXXX

  XXXX                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXX XXXXXX XXXXXX XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX XXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX XXXXXXXXXXX XXXXXX
                        XXXXXX
                            XXXX gettext(u'EAMENA Database | v3') XXXXX
                        XXXXXX
                    XXXXXX
                XXXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXX XXX XXXXXXXX    XXX
                        XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXX XXX XXXXXXXX XXX


               XXXXXXXXXXXX XXXXXXXX XXX
 XXXX                      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX X
                                    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                X
                            XXX

                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX X
                                    XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                                    XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXX
                                    XXXXXXXXX
                                    XXXXXXX XXXXXXXXXXX
                                        XXXXXX XXXX
                                    XXXXXXXXX
                                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                              XXXXXX
                                        XXXXXXX XXXX
                                XXXXXXX
                              XXXXXXXXXXXXXXXXXX
                            XXXX
                            XXXX XXXXXXXXXXXXXXXXXXXX
                              XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                              XXXXXX
                              XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                                        XXXXXXX XXXX
                                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                                        XXXXXX XXXX
                                    XXXXXXXXXX
                            XXXXXXXXXXXX
                            XXXXXXXXXXXXX XXX

                 XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXX
                            XXXXXXXX XXXXX X XXXX XXXXXXXXXX XXXXXXXXXXXX
                               XXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXX XXX XXXXX XXX
                XXXX XXXXX XXXX XXX
                    BB BBBBBBBBBBBBB BB BBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXX XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXXXXBBB BBBBBBBB BBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXXBBBBBXX gettext(u'Sign in') XXXX
                        XXXXXXX
                    BBBB
                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Welcome, ')  FFFFFFFFFFFFFFFFFFFFFXXXX
                            XX XXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXXXXBBB BBBBBBBB BBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXXBBBBBXX gettext(u'Log off') XXXX
                        XXXXXXX
                    BBBBB
                    XXXXXX
                                XXXXXXXXX XXX
                XXXX XXX XXXXXXXX XXXXXXXX XXX
XXXX                                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX                                    
                                    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                BBBBBBBBBB
                                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
                                        XXXXXXX XXXXXXXXXXXXXXXX
                                BBB BBBBBBBB BB BBBBBBBBBBBBB
                                            XXX XXXXXXXXXXXXXXX
                                                XXXXXXX XXXXXXXXBB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                                            XXXXX
                                BBBBBB
                                        XXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX
                                    XXXXXXX
                                XXXXX
                            XXXXX XXX

                    XXXX XXXXXXXXXXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXX XXXXXXX
XXXX                            XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXX
                               XXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXX XXXXX XXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Please read our Open Access Policy before using the database') XXXXXXXXXXX
                    BB BBBBBBBBBBBBB BB BBBBBBBBBBB
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXX gettext(u'Search the EAMENA Database') XXXXXXXXXXX
                    BBBB
                         XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXXBBBBBXX gettext(u'Public Access') XXXX
                        XXXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBBBBBBBBB
                        XXXXX XXXXXXXXX
                            XX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXXXX gettext(u'Create New Heritage Resources') XXXXXXXXXXX
                    BBBB
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXXBBBBBXX gettext(u'Register for Researcher Access') XXXXXXXXXXX
                                XXXX XXXXX XXX
                    BBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXXXXX XXX XXXXXX XXXXXX

    XXXX XXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXX XXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Home') XXXXXXX
                    XXXX
                XXXXX
                XXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Fast') XXXXXXX
                    XXXX
                XXXXX
                XXX XXXXXXXXX
  XXXX                  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Workflows') XXXXXXX
                    XXXX
                XXXXX
                XXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Search Tools') XXXXXXX
XXXX                    XXXX
                XXXXX
                XXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Mobile') XXXXXXX
                    XXXX
                XXXXX
            XXXXX
        XXXXXX

        XXXX XXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX X
                XXXX

                    XXXX XXXXX X XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u' Endangered Archaeology in') XXXX
                            XXX gettext(u' The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Tell Surezha (KRG, Iraq) © University of Chicago/Harvard University') XXXXXXX
                        XXXXXX
                    XXXXX


                    XXXX XXXXX X XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Faqra, Lebanon © Mohamed Kenawi') XXXXXXX
                        XXXXXX
                    XXXXX

                    XXXX XXXXX X XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBB BBBBB BB BBBBB BBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Suakin Island, Sudan © Colin Breen') XXXXXXX
                        XXXXXX
                    XXXXX


                    XXXX XXXXX X XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                       XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Agha Bozorg mosque, Kashan, Iran © Bijan Rouhani') XXXXXXX
                        XXXXXX
                    XXXXX


                    XXXX XXXXX X XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'St Catherine’s Monastery looking north, Sinai, Egypt, 1951 © John Clubb (683 Squadron RAF)') XXXXXXX
                        XXXXXX
                    XXXXX

                    XXXX XXXXX X XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Rock Art in Wadi Matkhandouch, Libya © Julia Nikolaus') XXXXXXX
                        XXXXXX
                    XXXXX

                    XXXX XXXXX X XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Shibam, Yemen on 2 November, 1929 © Nicholas Salt') XXXXXXX
                        XXXXXX
                    XXXXX

                    XXXX XXXXX X XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'A View of Petra, Jordan © Andrea Zerbini') XXXXXXX
                        XXXXXX

                    XXXXX

                    XXXX XXXXX X XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                          XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                       XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Historical buildings in Ardakan, Yazd, Iran © Bijan Rouhani') XXXXXXX
                        XXXXXX
                    XXXXX

                    XXXX XXXXX XX XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u' Endangered Archaeology in') XXXX
                            XXX gettext(u' The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Capitolium, Dougga, Tunisia © Nichole Sheldrick') XXXXXXX
                        XXXXXX
                    XXXXX

                    XXXX XXXXX XX XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Apadana Palace, Persepolis, Iran © Andrea Zerbini') XXXXXXX
                        XXXXXX
                    XXXXX


                    XXXX XXXXX XX XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Qasr Bounou, Morocco © The Middle Draa Project/Nichole Sheldrick') XXXXXXX
                        XXXXXX
                    XXXXX

                    XXXX XXXXX XX XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Aswan, Egypt © Mohamed Kenawi') XXXXXXX
                        XXXXXX
                    XXXXX

                    XXXX XXXXX XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBB BB BBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                       XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Sidon, Lebanon © Crystal el-Safadi') XXXXXXX
                        XXXXXX
                    XXXXX

                    XXXX XXXXX XX XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Nymphaeum, Garada/Umm Qais, Jordan © Andrea Zerbini') XXXXXXX
                        XXXXXX

                    XXXXX

                    XXXX XXXXX XX XXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX
                        XXXX XXXX XXXXX XXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB BB BBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXX XXX
                        XXXX XXX XXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'EAMENA Database v4.0') XXXXX
                            XXX gettext(u'Endangered Archaeology in') XXXX
                            XXX gettext(u'The Middle East & North Africa') XXXX
                        XXXXXX

                        XXXX XXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                        XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXX gettext(u'Lepcis Magna, Libya © Julia Nikolaus') XXXXXXX
                        XXXXXX
                    XXXXX


                XXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX

            XXXX XXXX XXXXXX XXX
            XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXX XXX XXXXX XXXXXXX XXX

    XXXX XXXX XXXXX X XXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXX

            XXXX XXXXXXX XXXX XXX
            XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Fast') XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Deploy Applications Rapidly') XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Design custom information management applications in hours.  Build your databases with Arches Designer, then configure your interface all without having to write any code.') 
                        XXXX
                    XXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXX XXX
            XXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX XXXXXXXXXXX XXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXX
            XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXX XXXX XXXX XXXXX XXX
                XXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXX gettext(u'Interface Manager') XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u"Arches automatically creates data entry forms based on your data models.  Use Arches' Card Manager to configure the look and feel of your data entry UI.") 
                        XXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXX XXXX XXXX XXXXX XXX
                XXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXX gettext(u'Data Security') XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u"Use Arches' Permissions Manager to set up data access rules for all your user groups and individual accounts.  You can define read/write/delete and no-access permissions.") 
                        XXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX

            XXXXXX
            XXXX XXX XXXXXXXXXXX XXX


        XXXXXXXXXX
    XXXXXXXXXX
    XXXX XXX XXXX XXXXX X XXX


    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX

        XXXX XXXXXX XXXXXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXX

            XXXX XXXXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXX

                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'EAMENA Project') XXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'University of Oxford') XXXX
                    XXXXXXXXX
                    XXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'University of Leicester') XXXX
                    XXXXXXXXX
                    XXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Durham University') XXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXX XXXXXX X XXX
            XXXX XXXXXXXXXXXXXXXXX

                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'MarEA Project') XXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'University of Southampton') XXXX
                    XXXXXXXXX
                    XXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Ulster University') XXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX


            XXXX XXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Supported By:') XXXXX

                 XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Arcadia Fund, a charitable fund of Lisbet Rausing & Peter Baldwin') XXXX
                    XXXXXXXXX
                    XXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'British Council Cultural Protection Fund') XXXX
                    XXXXXXXXX
                XXXXXX

                XXXX XXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Arcadia Foundation') XXXX
                                XXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'British Council Cultural Protection Fund') XXXX
                                XXXXX

                            XXXXX
                        XXXXXX

                        XXXXXXXX XXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'FAQ') XXXX
                                XXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Standards and Interoperability') XXXX
                                XXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Installation Guide') XXXX
                                XXXXX
                            XXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Arches Project Background') XXXX
                                XXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Arches Webinars/Presentations') XXXX
                                XXXXX
                                XXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Resource Models') XXXX
                                XXXXX
                            XXXXX
                        XXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXX XXXXXX XXX

    XXXX XXXXXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Terms & Conditions') XXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Privacy Policy') XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXX XXXXXXXXX XXXXXXXXX XXX



    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX


    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXX

            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
            XXX

            XXXXXXXX XXXXXX XX XXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX


            XXXXXXXX XXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX X XXXXXXXX
                    XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
                    XX X X XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX X XX X XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX X X X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                XXX
            X

            XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX
                XX
            X


        XXX

        XXX XXXXXXXXX X XXXXXXXXXXXXXXX XXXXX X
            XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

    XXXXXXXXX

XXXXXXX

XXXXXXX
