# Generated by Django 4.2.17 on 2025-02-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0002_create_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='curateddataset',
            name='zenodo_doi',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='curateddataset',
            name='zenodo_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
