# Generated by Django 4.2.17 on 2025-02-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0003_curateddataset_zenodo_doi_curateddataset_zenodo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curateddataset',
            name='zenodo_doi',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='curateddataset',
            name='zenodo_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
