# Generated by Django 4.2.17 on 2025-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0004_alter_curateddataset_zenodo_doi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curateddataset',
            name='ipfs_cid',
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
    ]
