BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX 
          XXXXXXXX 
          XXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXX XXXXXXXX 
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXX XXXXXX 
            XXXXXXXXXXXX XXXXXXX 
            XXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
