BBBB BBBBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX

XXXXXX
    XXXXXXX
    XXXXXXXX
XXXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXX
    XXXXXXX
    BB BBBB BB BB
    XX XXXXXXXXXXX XXXXXXFFFFFFFFFFFFFFXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
    XXXXXXX
XXXXXXX

XXXXXXX
