BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX
     gettext(u'X Coordinate Placeholder') 
XXXXXX
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Placeholder') X XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Y Coordinate Placeholder') 
XXXXXX
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Placeholder') X XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBB
XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXXX
BBBBBBBB BBBBBB
